token:
  expiration_time: 864000000
  secret: coffee_is_on_me

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: '00000000'
    url: jdbc:mariadb://localhost:3306/mooddb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root

logging:
  level:
    com.mood.userservice.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health